name = "JunctionTreesBenchmarks"
uuid = "b96aa7eb-521a-4b52-aa44-77d719efb0ad"
authors = ["Martin Roa Villescas"]
version = "0.1.0"

[compat]
julia = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
